name: lanars_test_task
description: "Lanars test task."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  logger: ^2.5.0
  objectbox: ^4.0.3
  objectbox_sync_flutter_libs: ^4.0.3
  photo_view: ^0.15.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.4

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0

  objectbox_generator: ^4.0.3
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true
